services:
  mongodb:
    image: mongo:8
    container_name: car-maintenance-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - car-maintenance-data:/data/db

volumes:
  car-maintenance-data:
